name: remote ssh command
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_ADDR }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script:
          cd /var/www/html && git pull origin main && composer install && php artisan migrate && systemctl restart apache2